json.id personalization_question.id
json.objectId personalization_question.objectId
json.detail personalization_question.detail
json.createdAt personalization_question.createdAt
json.updatedAt personalization_question.updatedAt