json.id network.id
json.objectId network.objectId
json.awesome_count network.awesome_count
json.image_url network.image_url
json.latitude network.latitude
json.longitude network.longitude
json.meetup_group_id network.meetup_group_id
json.time_zone network.time_zone
json.title network.title
json.createdAt network.createdAt
json.updatedAt network.updatedAt