json.id event.id
json.objectId event.objectId
json.featured event.featured
json.network_id event.network_id
json.updatedAt event.updatedAt
json.url event.url
json.event_date event.event_date
json.location event.location
json.title event.title
json.subscribe_count event.subscribe_count
json.createdAt event.createdAt
json.description event.description
json.meetup_event_id event.meetup_event_id
json.time_zone event.time_zone
json.hex_color event.hex_color